// Code generated by MockGen. DO NOT EDIT.
// Source: ./interactor.go

// Package popularkeyword is a generated GoMock package.
package popularkeyword

import (
	suggestion "go-clean-architecture/internal/entities/suggestion"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPresenter is a mock of Presenter interface.
type MockPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockPresenterMockRecorder
}

// MockPresenterMockRecorder is the mock recorder for MockPresenter.
type MockPresenterMockRecorder struct {
	mock *MockPresenter
}

// NewMockPresenter creates a new mock instance.
func NewMockPresenter(ctrl *gomock.Controller) *MockPresenter {
	mock := &MockPresenter{ctrl: ctrl}
	mock.recorder = &MockPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresenter) EXPECT() *MockPresenterMockRecorder {
	return m.recorder
}

// Present mocks base method.
func (m *MockPresenter) Present(popularKeyword suggestion.PopularKeyword, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Present", popularKeyword, err)
}

// Present indicates an expected call of Present.
func (mr *MockPresenterMockRecorder) Present(popularKeyword, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Present", reflect.TypeOf((*MockPresenter)(nil).Present), popularKeyword, err)
}
